# Generated by Django 6.1.1 on 2026-09-23 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم القسم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='المسمى الوظيفي')),
            ],
            options={
                'verbose_name': 'مسمى وظيفي',
                'verbose_name_plural': 'المسميات الوظيفية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='رقم البصمة')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم بالكامل')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/', verbose_name='الصورة')),
                ('status', models.CharField(choices=[('active', 'على رأس العمل'), ('inactive', 'غير نشط'), ('resigned', 'مستقيل'), ('terminated', 'تم إنهاء الخدمة')], default='active', max_length=15, verbose_name='الحالة')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='الرقم القومي')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], default='male', max_length=10, verbose_name='النوع')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'أعزب'), ('married', 'متزوج'), ('divorced', 'مطلق'), ('widowed', 'أرمل')], max_length=10, null=True, verbose_name='الحالة الاجتماعية')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('hire_date', models.DateField(verbose_name='تاريخ التعيين')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department', verbose_name='القسم')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب الدخول (للأتمتة)')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.jobtitle', verbose_name='الوظيفة')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفين',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('national_id', 'بطاقة الرقم القومي'), ('passport', 'جواز السفر'), ('certificate', 'شهادة'), ('contract', 'عقد العمل'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المستند')),
                ('file', models.FileField(upload_to='employees/documents/', verbose_name='الملف')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإصدار')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
            ],
            options={
                'verbose_name': 'مستند',
                'verbose_name_plural': 'المستندات والبطاقة/الباسبور',
            },
        ),
        migrations.CreateModel(
            name='EmployeeQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(max_length=200, verbose_name='المؤهل/الشهادة')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='جهة الحصول')),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سنة الحصول')),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='التقدير')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='employees.employee')),
            ],
            options={
                'verbose_name': 'مؤهل دراسي',
                'verbose_name_plural': 'المؤهلات والتأهيلات',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب الأساسي')),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='البدلات')),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الاستقطاعات')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='اسم البنك')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='رقم الحساب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='employees.employee')),
            ],
            options={
                'verbose_name': 'بيانات مرتب',
                'verbose_name_plural': 'بيانات المرتبات',
                'permissions': [('view_confidential_salary', 'يمكنه رؤية بيانات المرتب')],
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_type', models.CharField(choices=[('warning', 'إنذار'), ('deduction', 'خصم مالي'), ('suspension', 'إيقاف عن العمل'), ('other', 'أخرى')], max_length=15, verbose_name='نوع الجزاء')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='القيمة / عدد الأيام')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='employees.employee')),
            ],
            options={
                'verbose_name': 'جزاء',
                'verbose_name_plural': 'الجزاءات',
                'ordering': ['-date'],
            },
        ),
    ]
