# Generated by Django 6.1.1 on 2026-09-23 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نوع الإجازة')),
                ('deducts_balance', models.BooleanField(default=True, verbose_name='يخصم من رصيد الإجازات')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='يحتاج موافقة')),
                ('max_days_per_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='أقصى عدد أيام بالسنة')),
                ('color', models.CharField(default='#7C3AED', max_length=7, verbose_name='لون العرض (Hex)')),
            ],
            options={
                'verbose_name': 'نوع إجازة',
                'verbose_name_plural': 'أنواع الإجازات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=10, verbose_name='الحالة')),
                ('source', models.CharField(choices=[('manual', 'إدخال يدوي'), ('mobile', 'تطبيق الموبايل (Self-Service)')], default='manual', max_length=10, verbose_name='مصدر الطلب')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ تقديم الطلب')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(verbose_name='إلى تاريخ')),
                ('days_count', models.PositiveIntegerField(default=0, verbose_name='عدد الأيام')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة بواسطة')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='leaves.leavetype', verbose_name='نوع الإجازة')),
            ],
            options={
                'verbose_name': 'طلب إجازة',
                'verbose_name_plural': 'طلبات الإجازات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=10, verbose_name='الحالة')),
                ('source', models.CharField(choices=[('manual', 'إدخال يدوي'), ('mobile', 'تطبيق الموبايل (Self-Service)')], default='manual', max_length=10, verbose_name='مصدر الطلب')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ تقديم الطلب')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('from_time', models.TimeField(verbose_name='من الساعة')),
                ('to_time', models.TimeField(verbose_name='إلى الساعة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='employees.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة بواسطة')),
            ],
            options={
                'verbose_name': 'إذن',
                'verbose_name_plural': 'الأذونات',
                'ordering': ['-created_at'],
            },
        ),
    ]
