# Generated by Django 6.1.1 on 2026-09-23 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الجهاز')),
                ('ip_address', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('port', models.PositiveIntegerField(default=4370, verbose_name='البورت')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='الموقع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'جهاز بصمة',
                'verbose_name_plural': 'أجهزة البصمة (ZK)',
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_id', models.CharField(db_index=True, max_length=20, verbose_name='رقم البصمة')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='التوقيت')),
                ('punch_type', models.CharField(choices=[('in', 'حضور'), ('out', 'انصراف'), ('unknown', 'غير محدد')], default='unknown', max_length=10, verbose_name='نوع الحركة')),
                ('source', models.CharField(choices=[('zk', 'سحب من جهاز ZK'), ('excel', 'استيراد إكسيل'), ('manual', 'إدخال يدوي')], default='zk', max_length=10, verbose_name='المصدر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='attendance.attendancedevice')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='employees.employee')),
            ],
            options={
                'verbose_name': 'بصمة',
                'verbose_name_plural': 'سجل البصمات',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['fingerprint_id', 'timestamp'], name='attendance__fingerp_caf47b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='التاريخ')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('leave', 'إجازة'), ('permission', 'إذن'), ('weekend', 'إجازة أسبوعية')], default='present', max_length=12, verbose_name='الحالة')),
                ('worked_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ساعات العمل')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='employees.employee')),
            ],
            options={
                'verbose_name': 'ملخص يوم حضور',
                'verbose_name_plural': 'ملخص الحضور اليومي',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
